public class S5 implements Motor, Klima, Fren {
    
    public void eco(){
            System.debug('Audi S5 ekonomik motor kullanir...');
        }
    
    public void turbo(){
            System.debug('Audi S5 turbo motor kullanir...');
        }
    
     public void gas(){
            System.debug('Audi S5 gas motor kullanir...');
        }
    
    public void mevsimsel(){
            System.debug('Audi S5 mevsimsel klima kullanir...');
        }
    public void digital(){
            System.debug('Audi S5 digital klima kullanir...');
        }
    public void abs(){
            System.debug('Audi S5 abs fren kullanir...');
        }
    public void secure(){
            System.debug('Audi S5 secure klima kullanir...');
        }

}